---
 # file is parsed by inner-most keys only
 data:
     data_file: "data/sergio_8000_1.csv"
     debug: False
     batch_size: 16  # 1 for inference (for timing), 16 for train
     fci_vars: 5
     fci_batches: 10
     fci_batches_inference: 100
     fci_batch_size: 500
     envs_per_batch: 5
     num_workers: 10
     accumulate_batches: 1
     log_frequency: 10
     results_file: "results_fci_sergio_reproduce_1.npy"
 model:
     algorithm: "fci"
     model: "aggregator"
     num_vars: 1000
     num_edge_types: 8
     embed_dim: 64
     transformer_num_layers: 4
     n_heads: 8
     ffn_embed_dim: 8
     use_learned_sampler: False
 train:
     run_name: sc-rl
     patience: 100
     epochs: 10000
     min_epochs: 50
     lr: 5.e-5
     weight_decay: 1.e-5
     metric: "Val/auprc"
