---
 # file is parsed by inner-most keys only
 data:
<<<<<<< HEAD
     data_file: "data/data_test.csv"
     debug: False
=======
     data_file: "/Users/shreeyansarora/Downloads/SEA/sea-reproduce/src/data/hepar2.csv"
     debug: True
>>>>>>> 3e011a2 (Shreeyans changes)
     batch_size: 1  # 1 for inference, 16 for train
     fci_vars: 3
     fci_batches: 5
     fci_batches_inference: 5
     fci_batch_size: 20
     envs_per_batch: 5
     num_workers: 0
     accumulate_batches: 1
     log_frequency: 10
<<<<<<< HEAD
     results_file: "results_data.npy"
=======
     results_file: "predictions_hepar2.npy"
>>>>>>> 3e011a2 (Shreeyans changes)
 model:
     algorithm: "gies"
     model: "aggregator"
     num_vars: 1000
     num_edge_types: 5
     embed_dim: 64
     transformer_num_layers: 4
     n_heads: 8
     ffn_embed_dim: 8
     use_learned_sampler: False
 train:
     run_name: sc-rl
     patience: 50
     epochs: 10000
     min_epochs: 50
     lr: 1.e-4
     weight_decay: 1.e-5
     metric: "Val/auprc"
